#Config File example
save_dir: ./model/exp/night_test
model:
  arch:
    name: DLASeg
    num_layers: 34
    out_classes: [2, 16, 2]
    head_conv: 256


class_names: &class_names ['car','bus']  #Please fill in the category names (not include background category)
data:
  train:
    name: voc
    rootpath: /media/bihuasky/Files2/Dataset/night_car/Vehicle-Dataset-at-Night/all # voc2012存放目录
    class_names: *class_names
    output_size: [128, 128]
    img_path: /media/bihuasky/Files2/Dataset/night_car/Vehicle-Dataset-at-Night/all/JPEGImages  #Please fill in train image path
    ann_path: /media/bihuasky/Files2/Dataset/night_car/Vehicle-Dataset-at-Night/all/Annotations  #Please fill in train xml path
    input_size: [512,512] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.8, 1.2]
      saturation: [0.8, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: voc
    rootpath: /media/bihuasky/Files2/Dataset/night_car/Vehicle-Dataset-at-Night/all # voc2012存放目录
    class_names: *class_names
    output_size: [128, 128]
    img_path: /media/bihuasky/Files2/Dataset/night_car/Vehicle-Dataset-at-Night/all/JPEGImages  #Please fill in train image path
    ann_path: /media/bihuasky/Files2/Dataset/night_car/Vehicle-Dataset-at-Night/all/Annotations  #Please fill in train xml path
    input_size: [512,512] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0]
  workers_per_gpu: 1 #12
  batchsize_per_gpu: 6 # 160
schedule:
  # resume: model/exp/night_shapeloss/model_last.pth
  load_model: /media/bihuasky/TEYADI/school/nightcar/nightcar_hwdfl8_bsl_gflv2/model_best2/model_best_60.4.pth # model/centernet/ctdet_coco_dla_2x.pth #model/centernet/model_best_voc.pth
  optimizer:
    name: Adam
    lr: 0.0004
    # momentum: 0.9
    # weight_decay: 0.0001
  warmup:
    name: linear
    steps: 40 # 300
    ratio: 0.1
  total_epochs: 210 #160
  lr_schedule:
    name: MultiStepLR
    milestones: [10,50,100,150]
    gamma: 0.4
  val_intervals: 5 # 10
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10
